### ISSUE TITLE
Server list not shown if server-url is not provided

### ISSUE THREAD

**Issue by misaugstad** [Rhosys/openapi-explorer#111]
I have an OpenAPI spec yaml file located [here](https://raw.githubusercontent.com/ProjectSidewalk/SidewalkWebpage/2754-improve-api-documentation/api-test.yaml), which includes a list of servers like so
```
servers:
  - url: https://sidewalk-newberg-test.cs.washington.edu
    description: Test server for Newberg, Oregon
  - url: https://sidewalk-sea-test.cs.washington.edu
    description: Test server for Seattle, Washington
```

I tried to generate the docs without specifying the `server-url`, since the docs say that "when not specified defaults to the first listed server in the spec". But my servers section is empty (pictured below), and no server URL is available when executing queries.
![Screenshot from 2022-11-28 11-19-13](https://user-images.githubusercontent.com/6518824/204363948-8fe70ce1-97d0-4188-86f6-bc5b948bb6e5.png)

My HTML file looks like this:
```
<!doctype html>
<html>
  <head>
    <script type="module" src="https://unpkg.com/openapi-explorer@0/dist/browser/openapi-explorer.min.js"></script>
  </head>
  <body>
    <openapi-explorer spec-url="https://raw.githubusercontent.com/ProjectSidewalk/SidewalkWebpage/2754-improve-api-documentation/api-test.yaml"> </openapi-explorer>
  </body>
</html>
```

If I set the `server-url` to a URL that is not listed in the spec, it shows up. For example, if I set `server-url="https://sidewalk-amsterdam-test.cs.washington.edu"`, I get the following (the server listed in the HTML, plus those in the spec).
![Screenshot from 2022-11-28 11-17-49](https://user-images.githubusercontent.com/6518824/204364460-3e80e419-bb07-42d2-87ef-bb05a4b87475.png)

However, if I set the `server-url` to the URL of one of the servers that's already in the spec, I get the same result as when I don't specify the `server-url` at all! For example, if I set `server-url="https://sidewalk-newberg-test.cs.washington.edu"`, I see this again:
![Screenshot from 2022-11-28 11-19-13](https://user-images.githubusercontent.com/6518824/204364752-c9327b16-23b0-40f8-983b-7cd35bd8d12a.png)
