### ISSUE TITLE
Relative OAuth2 authorize/token URLs should resolve differently

### ISSUE THREAD

**Issue by max-mathieu** [Rhosys/openapi-explorer#39]
According to the specs here: https://swagger.io/docs/specification/authentication/oauth2/#relative-url
```
servers:
  - url: https://api.example.com/v2
components:
  securitySchemes:
    oauth2sample:
      type: oauth2
      flows: 
        authorizationCode:
          authorizationUrl: /oauth/authorize  # <-----
          tokenUrl: /oauth/token              # <-----
          scopes:
            ...
```
should become
```
authorizationUrl: https://api.example.com/oauth/authorize
tokenUrl: https://api.example.com/oauth/token
```

But my experience is that `openapi-explorer` resolves them to
```
authorizationUrl: https://api.example.com/v2/oauth/authorize
tokenUrl: https://api.example.com/v2/oauth/token
```
I will open a PR shortly with a proposed change, hoping you'll consider it!
